In [15]:
print("Hello")

Hello

In [16]:
import pandas as pd

In [17]:
row_sales = pd.read_csv("raw_sales.csv")
row_sales.head()
row_sales.info()
row_sales.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  5 non-null      int64
 1   customer  5 non-null      str
 2   Product   5 non-null      str
 3   price     5 non-null      int64
 4   quantity  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

       order_id          price  quantity
count  5.000000       5.000000  5.000000
mean   3.000000   30202.400000  3.000000
std    1.581139   44552.147297  2.828427
min    1.000000      12.000000  1.000000
25%    2.000000     500.000000  1.000000
50%    3.000000     500.000000  1.000000
75%    4.000000   50000.000000  5.000000
max    5.000000  100000.000000  7.000000

In [18]:
processed_sales = pd.read_csv("processed_sales.csv")
processed_sales.head()
processed_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     5 non-null      int64
 1   customer     5 non-null      str
 2   Product      5 non-null      str
 3   price        5 non-null      int64
 4   quantity     5 non-null      int64
 5   Total_Price  5 non-null      int64
dtypes: int64(4), str(2)
memory usage: 372.0 bytes

In [19]:
a=b=c=d=30
print(a,b,c,d)
print(a,a,a)
print(b,b)
print(c)

30 30 30 30
30 30 30
30 30
30

In [20]:
a = row_sales.shape
print('ok', a)

b = processed_sales.shape
print('processed', b)

c = row_sales.columns.tolist()
print('ok', c)  

d = processed_sales.columns.to_list()
print('processed', d)

ok (5, 5)
processed (5, 6)
ok ['order_id', 'customer', 'Product', 'price', 'quantity']
processed ['order_id', 'customer', 'Product', 'price', 'quantity', 'Total_Price']

In [21]:
import pandas as pd
df = pd.read_csv(
    "raw_sales.csv",
    header = 0,
    index_col = 0
    )
df.head()

         customer   Product   price  quantity
order_id
1           Rahul    Laptop   50000         5
2            Amit     Mouse     500         1
3           Sneha  Keyboard  100000         7
4            John   Monitor      12         1
5           Priya     Mouse     500         1

In [22]:
l= ["Date",1,2,5,'sai',[7,9,11]]
print(l)
print(l[0])
print(l[-2])
print(l[0:3])

['Date', 1, 2, 5, 'sai', [7, 9, 11]]
Date
sai
['Date', 1, 2]

In [23]:
f = 1
if f%2==0 and f%3==0:
    print("f is divisible by 2 and 3")
elif f%2==0:
    print("f is divisible by 2")
elif f%3==0:
    print("f is divisible by 3")
else:
    print("f is not divisible by 2 and 3")

f is not divisible by 2 and 3

In [24]:
for i in l:
    print(i)

Date
1
2
5
sai
[7, 9, 11]

In [14]:
##Pandas

In [25]:
a = l[1:5]

In [27]:
type(a)

list

In [28]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])

In [30]:
type(s1)

pandas.Series

In [31]:
d = {'R':[1,2,3,4,5], 'S':[6,7,8,9,10]}

In [33]:
df = pd.DataFrame(d)

In [35]:
type(df)

pandas.DataFrame

In [ ]:
import pandas as pd
df = pd.read_csv('raw_sales.csv')
df.head(1)
df.tail(1)
df.info()
df.columns
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  5 non-null      int64
 1   customer  5 non-null      str
 2   Product   5 non-null      str
 3   price     5 non-null      int64
 4   quantity  5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 332.0 bytes

(5, 5)

In [47]:
df['Product']

0      Laptop
1       Mouse
2    Keyboard
3     Monitor
4       Mouse
Name: Product, dtype: str

In [48]:
type(df['Product'])

pandas.Series

In [52]:
df[['Product','order_id']]

    Product  order_id
0    Laptop         1
1     Mouse         2
2  Keyboard         3
3   Monitor         4
4     Mouse         5

In [53]:
type(df[['Product','order_id']])

pandas.DataFrame

In [ ]:
input("Give me a String: ")

'something'

In [57]:
a = int(input("Enter a number to divide 60-40: "))
part1 = a*60//100
part2 = a*40//100
print("the 60-40 is : ",part1,"-",part2)

the 60-40 is :  600 - 400

In [59]:
a = int(input("Enter a number : "))
if a%2==0:
    print(a, " is even number")
else:
    print(a, "is odd number")

5 is odd number

In [64]:
a = int(input("Enter a number : "))

original = a
reverse = 0

while a>0:
    digit = a % 10 #a = 101, then 101%10=1, then 10%10=0, then 1%10=1
    reverse = reverse * 10 + digit #reverse = 0*10+1=1, then 1*10+0=10, then 10*10+1=101
    a=a//10 #a = 101//10=10, then 10//10=1, then 1//10=0
    print(a)
if original == reverse:
    print(original, "is a palindrome")
else:
    print(original, "is not a palindrome")

10
1
0
101 is a palindrome